### ISSUE TITLE
How do you execute Hy from PyCharm?

### ISSUE THREAD

**Issue by florisla** [Zedronar/hy-play#3]
Hi,

I'm using the same setup as you are (Hy, PyCharm, Python3).

In PyCharm, you cannot configure hy.exe as the Interpreter since it's 'not a valid home for Python SDK'.

Also, doing ``python.exe -m hy helloworld.hy`` fails -- it treats the .hy file as Python syntax.

So my ugly workaround is to start a python file instead which does nothing more than

    import hy
    import helloworld

Did you find a better approach by any chance?

**Comment by Zedronar** [comment]
Hi Floris! Sorry for the late response.

I did not find a better approach. I actually did the exact same thing. I think there's probably a better way though. Honestly, I didn't dedicate that much time to it.

Let me know if you do find a better way!

**Comment by florisla** [comment]
Will do, thanks.
